Repository open-cluster-management-io/policy-generator-plugin, pull requests merged in 2021-09, with the labels that each got.

#1 initial CI for policy-generator-plugin
  .github/workflows/linters.yml
  .github/workflows/unit-tests.yml
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Makefile
  OWNERS
  SECURITY.md
  build/common/Makefile.common.mk
  build/common/config/.golangci.yml
  build/common/config/.yamllint.yml
  build/common/config/mdl.rb
  build/common/scripts/lint_go.sh
  go.mod
  go.sum
  pkg/hello.go
  pkg/hello_test.go
Labels: lgtm

#2 Add support for configuring the plugin
  build/common/config/.golangci.yml
  go.mod
  go.sum
  internal/plugin.go
  internal/plugin_config_test.go
  internal/utils_test.go
  pkg/hello.go
  pkg/hello_test.go
Labels: lgtm, approved

#3 Use a package-level default variable to contain all policy defaults
  internal/plugin.go
Labels: lgtm, approved

#4 Add support for generating policies
  go.mod
  go.sum
  internal/plugin.go
  internal/plugin_test.go
  internal/utils.go
  internal/utils_test.go
Labels: lgtm, approved

#5 Add support for creating placement rules and placement bindings
  internal/plugin.go
  internal/plugin_test.go
Labels: lgtm, approved, dco-signoff: yes

#6 Add exec binary and readme
  .gitignore
  Makefile
  README.md
  cmd/main.go
  examples/input/configmap-aliens.yaml
  examples/input/patch.yaml
  examples/input/placementrule.yaml
  examples/input2/configmap-fish.yaml
  examples/input2/configmap-toads.yaml
  examples/kustomization.yml
  examples/policyGenerator.yaml
  go.mod
Labels: lgtm, approved, dco-signoff: yes

#7 Consolidate placement rules based on cluster selectors
  internal/plugin.go
  internal/plugin_test.go
Labels: lgtm, approved, dco-signoff: yes

#8 Fix faulty binding logic
  internal/plugin.go
Labels: lgtm, approved, dco-signoff: yes

#10 Add documentation
  README.md
  docs/policygenerator-reference.yaml
  docs/policygenerator.md
Labels: lgtm, approved, dco-signoff: yes

#9 Make default binding name optional
  internal/plugin.go
  internal/plugin_config_test.go
  internal/plugin_test.go
Labels: lgtm, approved, dco-signoff: yes

#14 Add support for Go v1.15
  cmd/main.go
Labels: lgtm, approved, dco-signoff: yes

#11 Add support for patching manifests
  docs/policygenerator-reference.yaml
  examples/policyGenerator.yaml
  go.mod
  go.sum
  internal/patches.go
  internal/patches_test.go
  internal/plugin.go
  internal/plugin_test.go
  internal/utils.go
  internal/utils_test.go
Labels: lgtm, approved, dco-signoff: yes

#12 Gatekeeper policy generation
  CONTRIBUTING.md
  docs/policygenerator-reference.yaml
  docs/policygenerator.md
  examples/input-folder/configmap-fish.yaml
  examples/input-folder/configmap-toads.yaml
  examples/input-gatekeeper/gatekeeper.yaml
  examples/input-kyverno/kyverno.yaml
  examples/policyGenerator.yaml
  internal/expanders/expanders.go
  internal/expanders/expanders_utils_test.go
  internal/expanders/gatekeeper.go
  internal/expanders/gatekeeper_test.go
  internal/expanders/kyverno.go
  internal/expanders/kyverno_test.go
  internal/plugin.go
  internal/types/types.go
  internal/utils.go
Labels: lgtm, approved, dco-signoff: yes

#16 Address comments from #12
  docs/policygenerator.md
  internal/expanders/gatekeeper_test.go
Labels: lgtm, approved, dco-signoff: yes

#13 Add-option-to-not-consolidate-under-single-ConfigurationPolicy-#15836
  docs/policygenerator-reference.yaml
  internal/plugin.go
  internal/plugin_test.go
  internal/types/types.go
  internal/utils.go
  internal/utils_test.go
Labels: lgtm, approved, dco-signoff: yes

#19 Build the release binaries statically
  .gitignore
  Makefile
Labels: lgtm, approved, dco-signoff: yes

#20 Update link
  docs/policygenerator.md
Labels: lgtm, approved, dco-signoff: yes
